export const icons = {
	smartphones: "📱",
	laptops: "💻",
	fragrances: "🌸",
	skincare: "🧴",
	groceries: "🛒",
	"home-decoration": "🏠",
	furniture: "🛋️",
	tops: "👚",
	"womens-dresses": "👗",
	"womens-shoes": "👠",
	"mens-shirts": "👔",
	"mens-shoes": "👞",
	"mens-watches": "⌚",
	"womens-watches": "⌚",
	"womens-bags": "👜",
	"womens-jewellery": "💍",
	sunglasses: "🕶️",
	automotive: "🚗",
	motorcycle: "🏍️",
	lighting: "💡",
};
